name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  NETCORE_VERSION: "8.0.x"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  REGISTRY: ${{ secrets.REGISTRY_ADDR }}
  SRC: "/home/runner/work/veritas/veritas/src"

jobs:
  test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Get dotnet version ğŸ“
        id: get_version
        run: |
          echo "::set-output name=version::$(dotnet --version)"

      - name: Load cache ğŸ”ƒ
        uses: actions/cache@v4
        with:
          path: |
            **/bin
            **/obj
          key: |
            ${{ runner.os }}-dotnet-${{ steps.get_version.outputs.version }}-${{ hashFiles('**/*.csproj') }}

      - name: Restore packages ğŸ“¦
        run: dotnet restore

      - name: Test ğŸ§ª
        run: dotnet test --no-restore -v normal

  docker-build-and-push:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up QEMU ğŸ› ï¸
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx â
        uses: docker/setup-buildx-action@v3

      - name: Docker login ğŸ”‘
        uses: docker/login-action@v3
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
        with:
          registry: $REGISTRY
          username: $REGISTRY_USER
          password: $REGISTRY_PASS

      - name: Build and push ğŸ› ï¸
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "$REGISTRY/veritas-api:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max


  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    steps:
      - name: Restart docker-compose ğŸ”
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          # TODO add the images here
          script: |
            
            docker compose down
            docker pull $REGISTRY/veritas-api:latest
            docker compose up -d